# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Semantic versioning and Build
    runs-on: ubuntu-latest
    outputs:
      release-tag: ${{ steps.release.outputs.tag }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install build tools
        run: |
          make install-dev
      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          make build
          ls dist
      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

  publish-to-github:
    name: Publish to GitHub
    needs:
      - build
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: |
            ./dist/*.tar.gz
            ./dist/*.whl
      - name: Publish package distributions to GitHub Releases
        uses: python-semantic-release/upload-to-gh-release@v9.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{needs.build.outputs.release-tag}}

  publish-to-testpypi:
    name: Publish to TestPyPI
    needs:
      - build
      - publish-to-github
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://pypi.org/p/tmp-python-sample-yn1205

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download the distributions from release
        run: gh release download ${{needs.build.outputs.release-tag}} -D dist -p '*.tar.gz' -p '*.whl'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.REPOSITORY }}
      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  test:
    name: Integration Test
    needs:
      - build
      - publish-to-testpypi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{needs.build.outputs.release-tag}}
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install
        run: |
          tag=${{needs.build.outputs.release-tag}}
          pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple tmp-python-sample-yn1205==${tag:1}
          pip install pytest
      - name: Run test
        run: make it

  publish-to-pypi:
    name: Publish to PyPI
    needs:
      - build
      - test
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/tmp-python-sample-yn1205

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download the distributions from release
        run: gh release download ${{needs.build.outputs.release-tag}} -D dist -p '*.tar.gz' -p '*.whl'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.REPOSITORY }}
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1