# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install build tools
        run: |
          make install-dev
      - name: Build
        run: |
          make build
      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: |
            ./dist/*.tar.gz
            ./dist/*.whl
      - name: Create release
        shell: bash
        run: |
          git config --global user.name "semantic-release (via Github actions)"
          git config --global user.email "semantic-release@github-actions"
          semantic-release version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Download all the dists
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: python-package-distributions
      #     path: dist/
      # - name: Sign the dists with Sigstore
      #   uses: sigstore/gh-action-sigstore-python@v2.1.1
      #   with:
      #     inputs: >-
      #       ./dist/*.tar.gz
      #       ./dist/*.whl